### ISSUE TITLE
MIDI: Option to merge-thru midi input to output

### ISSUE THREAD

**Issue by grrrwaaa** [electro-smith/oopsy#13]

**Comment by grrrwaaa** [comment]
Question about how to configure this. Perhaps use [in 5 midi_thru] or [out 5 midi_thru] to signal it to oopsy? Or a checkbox in the oopsy bpatcher / flag to oopsy.js?

**Comment by manysounds** [comment]
[in 5 midi_thru_out5] feels best for future implementations, i.e. other hardware platforms, including roll your own Oopsy hardware designations for "who knows what"
