### ISSUE TITLE
OSX on M1 archs; os library paths may be different

### ISSUE THREAD

**Issue by grrrwaaa** [electro-smith/oopsy#37]
Based on Alius' feedback from working from an M1 macbook pro, it seems that homebrew installs things to /opt/homebrew rather than /usr/local

Easy enough to have oopsy.js use a different prefix path accordingly, but would require some kind of detection method. 

Perhaps the smartest thing would be for oopsy.js to test for the existence of the gcc-arm-embedded binaries in likely locations, and use the path of whatever is found (by some priority such as modified date in the case of multiple hits?)

By the same method, it could test for dfu-util etc., which will likely be more helpful user feedback too!

**Comment by ABmod** [comment]
Yes, by default on M1 homebrew installs to /opt/homebrew. I changed paths in oopsy.js and it compiles nicely. We need to find arch type so we could switch path for intel or mac m1 (arm64). the problem here is that bundled nodeJs in Max is Version: v12.14.1. Since nodeJS 15.5 process.arch can return arm64. (https://nodejs.org/api/process.html#process_process_arch).
or we could reach cpu architecture some other way?

So for now i guess only simple solution is to install things under terminal running in rosetta?

**Comment by grrrwaaa** [comment]
Suggesting adding this test at teh start of oopsy.js:

```js
let build_tools_path;
function checkBuildEnvironment() {
	// check for available build tools:
	if (os.platform == "win32") {
		// TODO
	} else {
		// OSX:
		let locations = ["/opt/homebrew/bin", "/usr/local/bin"]
		for (loc of locations) {
			if (fs.existsSync(`${loc}/arm-none-eabi-gcc`)) {
				build_tools_path = loc;
				console.log(`using build tools found in ${build_tools_path}`);
				break;
			}
		}
		if (!build_tools_path) {
			console.log("oopsy can't find an ARM-GCC toolchain. Please check https://github.com/electro-smith/DaisyWiki/wiki/1e.-Getting-Started-With-Oopsy-(Gen~-Integration) for installation instructions.")
			process.exit(-1);
		}
		if (!fs.existsSync(`${build_tools_path}/dfu-util`)) {
			console.warn(`oopsy can't find the dfu-util binary in ${build_tools_path}, will not be able to upload binary to the Daisy. Please check https://github.com/electro-smith/DaisyWiki/wiki/1e.-Getting-Started-With-Oopsy-(Gen~-Integration) for installation instructions.`)
		}
	}
}```

And this kind of insert in the actual build calls: 

```js
console.log(execSync(`export PATH=$PATH:${build_tools_path} && make`, { cwd: build_path }).toString())
```

That would a) use /opt/homebrew/bin if it exists, else it will use /usr/local/bin if it exists, else it will flag an error to the user and invite them to follow the instructions at https://github.com/electro-smith/DaisyWiki/wiki/1e.-Getting-Started-With-Oopsy-(Gen~-Integration)

I'm just wondering if there are any other similar paths that we should also include, i.e. other locations that somebody might have installed arm-none-eabi-gcc to?

**Comment by ABmod** [comment]
well on m1 it will install in /opt/homebrew as stated here: https://docs.brew.sh/Installation. so if one follows instructions all should be ok. and your idea to just check both locations is great!

**Comment by grrrwaaa** [comment]
OK that change is now pushed to the dev branch

**Comment by ABmod** [comment]
updated to new dev branch, and it stoped putting stuff to field.  dfu is not starting?



oopsy-verbose: oopsy generated code
oopsy-verbose: generated code
oopsy-verbose: rm -fR build
oopsy-verbose: 
oopsy-verbose: mkdir build
oopsy-verbose: created binary 63KB
oopsy-verbose: done
oopsy-verbose: arm-none-eabi-gcc -c -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard  -DUSE_HAL_DRIVER -DSTM32H750xx -DUSE_HAL_DRIVER -DHSE_VALUE=16000000 -DSTM32H750xx  -I../libdaisy -I../libdaisy/src/ -I../libdaisy/src/usbd -I../libdaisy/Drivers/CMSIS/Include/ -I../libdaisy/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../libdaisy/Drivers/STM32H7xx_HAL_Driver/Inc/ -I../libdaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../libdaisy/core/ -I  -O3 -Wall -Wno-missing-attributes -fasm -fdata-sections -ffunction-sections -MMD -MP -MF"build/startup_stm32h750xx.d" -I"../gen_dsp" -O3 -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -std=gnu11 -Wa,-a,-ad,-alms=build/startup_stm32h750xx.lst ../libdaisy/core/startup_stm32h750xx.c -o build/startup_stm32h750xx.o
oopsy-verbose: arm-none-eabi-g++  -c -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard  -DUSE_HAL_DRIVER -DSTM32H750xx -DUSE_HAL_DRIVER -DHSE_VALUE=16000000 -DSTM32H750xx  -I../libdaisy -I../libdaisy/src/ -I../libdaisy/src/usbd -I../libdaisy/Drivers/CMSIS/Include/ -I../libdaisy/Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../libdaisy/Drivers/STM32H7xx_HAL_Driver/Inc/ -I../libdaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../libdaisy/core/ -I  -O3 -Wall -Wno-missing-attributes -fasm -fdata-sections -ffunction-sections -MMD -MP -MF"build/pulsar_field.d" -I"../gen_dsp" -O3 -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -fno-exceptions -fasm -finline -finline-functions-called-once -fshort-enums -fno-move-loop-invariants -fno-unwind-tables  -O3 -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -std=gnu++14 -Wa,-a,-ad,-alms=build/pulsar_field.lst pulsar_field.cpp -o build/pulsar_field.o
oopsy-verbose: arm-none-eabi-g++  build/startup_stm32h750xx.o build/pulsar_field.o   -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard --specs=nano.specs --specs=nosys.specs -T../libdaisy/core/STM32H750IB_flash.lds -L../libdaisy/build  -ldaisy -lc -lm -lnosys -Wl,-Map=build/pulsar.map,--cref -Wl,--gc-sections -o build/pulsar.elf
oopsy-verbose: arm-none-eabi-size build/pulsar.elf
oopsy-verbose:    text	   data	    bss	    dec	    hex	filename
oopsy-verbose:   63632	    864	67134276	67198772	4015f34	build/pulsar.elf
oopsy-verbose: arm-none-eabi-objcopy -O ihex build/pulsar.elf build/pulsar.hex
oopsy-verbose: arm-none-eabi-objcopy -O binary -S build/pulsar.elf build/pulsar.bin
oopsy-verbose: 
oopsy-verbose: oopsy created binary 63KB
oopsy-verbose: oopsy done

**Comment by ABmod** [comment]
i think the problem is here 63/64 line in oopsy.js

if (fs.existsSync(`${build_tools_path}/dfu-util`)) {
			has_dfu_util = false;

**Comment by grrrwaaa** [comment]
Yes it should! Stupid human logic error. Will fix immediately.

**Comment by tommyecho** [comment]
Hi! This thread is above my paygrade, but I was successful in using oopsy in max with the daisy patch when I was using my old intel macbook pro. Now I'm on an M1 mac and am getting an error message "arm-none-eabi-gcc" cannot be opened because the developer cannot be verified. It says when homebrew cask downloaded it from developer.arm.com. but says macOS won't open it because of malware concerns. Can anyone advise me on how to get past this? Thanks!

**Comment by stephenhensley** [comment]
@tommyecho We've updated the wiki articles for [installing the toolchain on MacOS](https://github.com/electro-smith/DaisyWiki/wiki/1b.-Installing-the-Toolchain-on-Mac). 

After the brew install, there is a security command that will run. If you don't want to go through (not sure if this will resolve the issue on an M1 mac, but it does resolve a similar issue on OSes more recent than Mojave.

If you don't feel like downloading the installer (it basically just wraps up the brew install, and security fix into a script that can be double clicked). The security specific commands are:

```
find /usr/local/Caskroom/gcc-arm-embedded -type f -perm +111 -print | xargs spctl --add --label "gcc-arm-embedded"
find /usr/local/Caskroom/gcc-arm-embedded | xargs xattr -d com.apple.quarantine
```

**Comment by tommyecho** [comment]
Thanks for the quick response! There was nothing to doubleclick and install (besides unzipping the zip. I followed the readme as best as I could, but I don't think I understand what is meant by "drag the OS" directory. I then entered the two lines of code you posted above, but it doesn't seem to have worked. Here is everything that was posted in the terminal after doing these things:

**Comment by tommyecho** [comment]
Last login: Tue Apr 20 14:56:01 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Pro:~ DrEcho$ cd /Users/DrEcho/Documents/DaisyToolchain-0.3.1/macOS/install.command 
-bash: cd: /Users/DrEcho/Documents/DaisyToolchain-0.3.1/macOS/install.command: Not a directory
MacBook-Pro:~ DrEcho$ find /usr/local/Caskroom/gcc-arm-embedded -type f -perm +111 -print | xargs spctl --add --label "gcc-arm-embedded"
objc[44861]: Class SPExecutionPolicy is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[44861]: Class AppWrapper is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[44861]: Class AppWrapperPolicyResult is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[44861]: Class AppWrapperPolicy is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[44861]: Class SPLog is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[44861]: Class MIS is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[44861]: Class SPExecutionHistoryItem is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[44861]: Class SPExecutionPolicyItem is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[44861]: Class SPDeveloperPolicy is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
objc[44861]: Class GKScanResult is implemented in both /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy and /usr/sbin/spctl. One of the two will be used. Which one is undefined.
MacBook-Pro:~ DrEcho$ find /usr/local/Caskroom/gcc-arm-embedded | xargs xattr -d com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/.metadata: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/.metadata/config.json: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/.metadata/10-2020-q4-major: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/.metadata/10-2020-q4-major/20210317210902.678: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/.metadata/10-2020-q4-major/20210317210902.678/Casks: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/.metadata/10-2020-q4-major/20210317210902.678/Casks/gcc-arm-embedded.rb: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/10-2020-q4-major/gcc-arm-none-eabi-10-2020-q4-major/lib/gcc/arm-none-eabi/10.2.1/plugin/libcc1plugin.so: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/10-2020-q4-major/gcc-arm-none-eabi-10-2020-q4-major/lib/gcc/arm-none-eabi/10.2.1/plugin/libcp1plugin.so: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/10-2020-q4-major/gcc-arm-none-eabi-10-2020-q4-major/lib/gcc/arm-none-eabi/10.2.1/liblto_plugin.0.so: No such xattr: com.apple.quarantine
xattr: /usr/local/Caskroom/gcc-arm-embedded/10-2020-q4-major/gcc-arm-none-eabi-10-2020-q4-major/lib/libcc1.so: No such xattr: com.apple.quarantine
MacBook-Pro:~ DrEcho$

**Comment by tommyecho** [comment]
Thank you for the quick reply! I actually went back and redid the install of the toolchain by entering this command line from the setup page and things seem to be working well!

brew install make armmbed/formulae/arm-none-eabi-gcc dfu-util

**Comment by stephenhensley** [comment]
@tommyecho sorry for any confusion. Once downloaded, the zip has a `macOS/install.command` file that can be clicked that essentially does what you did, and then runs those security commands. 

However, if that's not needed with the `armmbed/formulae/arm-none-eabi-gcc` formula it might be worth us looking into making that our default everywhere.

Thanks for the feedback! Glad you got up and running :)
