### ISSUE TITLE
Patch menu OLED bug

### ISSUE THREAD

**Issue by LLT44** [electro-smith/oopsy#38]
Here I am, LLT, following our discussions on the C74 forum. you will find attached the patch

<pre><code>
----------begin_max5_patcher----------
2348.3oc4bs0aiaiE94L.y+AA+XQFGQRcsOMK1tEnO0Aam8ghhBCZKZGNQVT
PjNWZwt+1WJRIqKVVhxMxNN8gDYQRIcNemq7HJ9me7C2LaI6YBel02a8aV2b
yeJa4FUa4sbSYC2LaK94UwXtZfyVw1tkjHlcaQmBxyBUGekrMMFKHVqYYV+.
lxe4Goj3n8CbMKQjf2RTC9ejQwwV+j.GSWseDzHUerke6SPm8slhEqtmlrYQ
FYkPSqPm412ZAg5+CTG7maa86kWSxtszjXhPQxf5T.m9GJJ.DHuppQy1IJGt
sp0+6G+P9Q4gaMFZH+QDd0+qK1AfFlcbbBTGbK++QXG3qMYGSejLeCllTQ5O
hy1Kp5n6TblrWAIaAIAuLlz.k0zj3kThl6lwoaRvwyts9ux+acLCKx+QLkKQ
h8bqjvjPDNIgDuhsKQAR1cApfgAUjCTis4+OzdrfpaYyb7ijnEXgHitbmfT8
KdAxVBs4XW7NBacY666nNrEyR1zC.2XrakBq7w4sWgsU2zj7t+juc2CfeOKS
X5CqTr04cZWBUvEunk2NECnPiq5GmhJ3Rk.jjUo.RIO8HkSWRiohWZpesdMm
THjyYYqFR0X1pGHQQY3M7UYr33FJOqjdadPbeFa2l6azgVM99NtDcOO1QOK2
rkEQZ1DKKRxD0a5XVC0zCKEMQjsLtTgOZtDaRwUtXwYaJbRO6ywLVpzlAHMa
97ZpTTH+w2jZSwuLGSWW61VyPweX6DWWsuT0Af8w89bDmlfSVzmPdRRic544
G+2+zW9hzVIleXzlMjZ9iF1kSm3hANkggJULPn1ah2vNPpGjQcO5DufMdxZc
lFdQxksORx3TVRcseoxPZZs1a4gYK9aL08Jnx9URj51.UskQxMtJt00r0wYR
XPHwfcYZQvydN07SjqvmkriVIw0B6RZSIUyEe7T7pBkZd5borZ+MYVEBCzZa
HajVoKTcpeHrFHmaloMoa3UZFKkjPSRyHbYtHXQAqT0eDYMdWrXQiP9v4cOf
0EDa281LmkJFYSFMhkjSHMEP4sW9HkLo1hxsAOoFRBNsqKWpXJQni0KWxr63
KwYJmiZOwv88JXr3l8Uckwj0hh9SoxXqs.TAKsmdynatuuqdIS161du8pt3x
XH5tWjGkeQdX0VCDGGW3Rn0S3YbBcqL+RAUKOf1U8df+aPqtdrqthjVAqHOQ
iD5nAMTOjW.MsTwZVkXOhtgvEsZTf0dnq0z9.k0aaWYftEhhrkaMBo8iLYHY
H6m3EirT8qATTkzdC6+5Naa1QuNca5YUFfg+x7Uhr347sLl3dTiwcfu1JeqG
3e0twU1kSVO+4t2ZE.0d.BJSqu4sryr4OZPnFIkrOXzqON8cmLr.FBVB03Qd
3las7bL.UfW+nBbPkEIF3dkBKpjnsV8nyBYTqchGYwVeVRmReNxi3ms.xiEA
cjs4NJPrmfTswXGCMHc0fafIXrcaZoq3sWZ7+0yoFHbHLzCflCkfnCx8Jzs1
qGRELDP45YWCf9aKNgLDmtNiRJIXa6S1XyTUHcLAGz0Dzb5nxfVV.eeMRnsr
BGqa72BgJAKhheYAmrhkDwKiVZCzwKQvZALAdymn.lPeCU.0.MBF9dIfYJg7
fUdwlnIDN2BZ84hRxlWC.qmxvoC.4EE48zyUYP2hN1pJ+ib0fti6XSHzbrGc
Vw96kSAjk8xo5d.NXFJ.j9MNXq7R33cM40bULM05S.KvICOdCpXEBTIAqeAS
tn+dAOCgNH+fqVzYK84SNnqsg.iienwyOE8N.XL0b5pDW9NUNGSU1ECFhCY6
TyVyANVas2pYWHG01zoBUMdRCEkYyCM22cbpjuUw0sxDG3RnkOUXqsoXq1L2
+ciFaJ6ARs7gapiYN.B7MrJmt9N5Y6CFq6RyQP6KIBZepHnmYUO+8G.FgE3Z
.nSfsssEzfogcpV6.2gfZeY7I+pZxCPnoa9uvyJXOUw7ANFN4rSt1MuYi4mu
VtpVhOSTYC.HSwWWu8q0kox+v4srAxGbK2Ai.1flNoXsaUj+zEX29hTtQTd4
FkSC5R7d4..iemR5R1.88d2TnwB7GpJ2aFYCIoPDnk.ggyCqjA9SkHHzvohU
H.P1v2KB.ITC0H9mJJt9TE6yzbeg5EDFz8cDDCNOPrqYIG+tCgyi8cpyIywz
Jdd4B8UasCFmm8+QV8WJZOe.GAN4rcYqJ0wJ75Y0hMhHbAMY+Rp72pJUU9HM
WnNZZIvTZAL4jhuojR9hVZhoEOiEQdSNs3ZLtL8xn70xjgDi8zSL4lG.SHFO
8.mZZwLCI6omXflRLcnmukFkxnIhB2cPTQ8ZUSL1UWXG0YMurpOBi2DLFnCu
I6IQvTRh.iIQu29jn8f5G4k5KuVTApJPiBz0OIv9xneXOpXHf9070KmG.HTk
dbsydayYfQxY.GO0gd3rIUazTFKXxCn.CGk6k9AYfCRM0U8Z6E5izq5C+Kh5
yH3LuC4ryhd.z77+ldEAiy+CL84hBQiRqDdITuPiR8B1qgCBT7wQFnCrnLiT
mcIzJMOVIZPNy0SGJAob3BgUmMsJPFG6.N8yfv3L3blbRADNlzj6Wz5Agp2I
mS4mxg2kzcu4blJCuQwZNnAijMkFjffQYPNsSzB3NJKK3zRLNiBYlXaKiiHz
0Lm6NUJj9CjxAXu+rKgskwbVWIccdrQLOnU3zqIXdzmomVLlT5u5UkcT8Y3W
rWkn+Nx6aiJg7bJKSrlEWnGL6e9828e3jL9cw3cYj69AB+AAK8te9m+xu7qK
95+5W95cUenx5Ktqspg+56FH4z7N5w2cGpsaNjOT8pKn42KRm6oP8tcOnWvZ
AEqVnCWGKGYOE50Zav3z34Zuzzt3XGC33hE.Av095fkKeO8cwud8yugZFELO
.F35CbT+GE5bEw8Ue+vcw+Alv+9Ny8KY97+6bY3+2ua4O6cJp+DQ6Yy7QHOg
n1BrVq1pz5bWpIrOgpaQR95pnUrjwfAiUL1dyCSe0MeWiEh01Q5JEtC7Rz5o
.JUk3ocZScpWYLADXJATFc8u1iyeDOtC3Wvq.A3cd4Wmy6iCYxiC.d0ddvyK
60JQYSltzqvCDXzCDbvCrv+Pq8hJ0yp8dPU68ept16o5Yem5f8bphDc6ZulJ
OhyG+fb.+e3DZDtM
-----------end_max5_patcher-----------
</code></pre>

**Comment by grrrwaaa** [comment]
Hi there, thanks for posting the patch!

[For reference, the bug was reported as this patch making the OLED/encoder menu on the Daisy Patch non-functional, here: https://cycling74.com/forums/oopsy-daisy-—-an-introduction-part-2/replies/1#reply-604a4a1666dbaf6d4136a0b9]

Reproduced here. Interesting note: if I upload from the terminal, it works fine. If I upload from Max, it fails. 

There's a timeout error being driven by the maxAPI handler while re-routing stdout, which might be the cause, or might just be a symptom.  Will keep investigating.

**Comment by grrrwaaa** [comment]
I have found the error -- you were using the template for the Daisy Field, not for the Daisy Patch!  They have different software APIs and require different binaries. 

Simple fix: In your Max patcher, delete the oopsy bpatcher and add a new object, type in "oopsy.patch", and you should be fine.
