### ISSUE TITLE
No MIDI IO in the latest dev version. And no param visible on the OLED screen

### ISSUE THREAD

**Issue by LLT44** [electro-smith/oopsy#43]
Hello since I installed the last correction of the dev version, I no longer have midi in out in the Daisy Patch. 
And the params are no longer visible in the OLED screen. 
I am using windows 10 and Max 8.1.10

For the midi did a simple thing [in 5 midi] in [out 5 midi] to pass the midi information in my other devices and it worked very well.
 I must be missing something in a new midi param syntax

LLT

**Comment by LLT44** [comment]
Now with your new fixes (thanks) MIDI is ok. But no param is displayed on the OLED screen

**Comment by grrrwaaa** [comment]
Just pushed a fix for the missing param view. 

I'm still debugging MIDI output though -- I'm seeing some dropped output messages and trying to chase down where that's happening.

**Comment by grrrwaaa** [comment]
Argh! I'll get this right eventually...

Actually I'm trying to get rid of the generic [midi N out] in favour of dedicated midi outputs, such as [out N midi_bend] or [history midi_cc1_out] etc. So far, cc, bend, and fixed-note vel/drum outs are working. Next up is generalized note outputs, which is a bit more complex, but will probably work on a per-voice basis like this:

[history midi_note1_pitch_out], [history midi_note1_vel_out], 
[history midi_note1_press_out], etc.
[history midi_note2_pitch_out] etc.

**Comment by LLT44** [comment]
Argh! I understand well :)
If you get rid of the generic output, will there be a way to pass MIDI IO seamlessly through the Daisy?
Let me explain:
If I am not using the MIDI functions of the Daisy, I still need the MIDI IO so that my other devices can talk to each other

**Comment by LLT44** [comment]
Yes you are right that sounds great.
If we use [in 1 midithru] we can also use at the same time [out N midi_bend] or [history midi_cc1_out] etc for example?

**Comment by grrrwaaa** [comment]
Yes, exactly, that's what I'm thinking. 

Also [param midi_cc1] etc should also work at the same time.

**Comment by LLT44** [comment]
It's great, thank you for everything you do. 
I haven't used the SD functions yet, probably in the next few days

**Comment by grrrwaaa** [comment]
OK, a whole ream of changes to MIDI output is now in `dev`:

- API change: [out N midi*] no longer supported. Use [history midi_*_out] instead. Raw MIDI output was causing unpredictable behaviour and could overload the MIDI baud rate too easily. Better handlers for specific MIDI messages have been added instead.
- Added support for history-based MIDI outputs:
    - [history midi_cc1_out], [history midi_cc11_ch2_out], etc.: 0..1 outputs midi CC (default channel 1)
    - [history midi_bend_out], [history midi_bend_ch2_out], etc.: -1..1 outputs midi CC (default channel 1)
    - [history midi_press_out], [history midi_press_ch2_out], etc.: 0..1 outputs midi channel pressure (default channel 1)
    - [history midi_program_out], [history midi_program_ch2_out], etc.: 0..127 outputs midi program change (default channel 1)
    - [history midi_drum36_out] etc.: 0..1 outputs note velocity on channel 10
    - [history midi_vel36_out], [history midi_vel36_ch2_out] etc.: 0..1 outputs note velocity (default channel 1)
    - [history midi_clock_out], [history midi_stop_out], [history midi_start_out], [history midi_continue_out], [history midi_reset_out], [history midi_sense_out]: rising edge gate outputs transport etc. midi messages
  - Added midi note output mechanics:
    - [history midi_note1_pitch_out] and [history midi_note1_vel_out] at minimum required to create a note out. Use note1, note2, noteN etc. to define your polyphony.
    - [history midi_note1_chan_out] and [history midi_note1_press_out] are optional for setting a midi channel (other than channel 1) and polyphonic pressure (aka polyphonic aftertouch)
  - Added [in N midithru], which works the same as [in N midi] (giving you raw bytes scaled by 1/256), but also passes all MIDI received in the hardware input through to the hardware output

**Comment by grrrwaaa** [comment]
Going to close this one out now, but let me know if you have any trouble & I can re-open.

**Comment by LLT44** [comment]
Hello,
Fantastic! I just tested [in 5 midithru] in [out 5 midi] and it works.
I pass 5 different MIDI channels with several notes all at 120BPM. There have been times of MIDI freeze on my devices. With a reset of the Daisy it works again. Difficult to be more precise it seems random.
