### ISSUE TITLE
Typo in oopsy.js max apps error message

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/oopsy#47]
lines 145-148 of `oopsy.js`
```
if (hardware.max_apps && cpps.length > hardware.max_apps) {
     console.log(`this target does not support more than ${hardwre.max_apps} apps`)
     cpps.length = hardware.max_apps
}
```

`hardwre` should be `hardware`

I didn't check if this is resolved on `dev` or not yet, but figured better to put it somewhere than forget about it before I check.

**Comment by grrrwaaa** [comment]
Yeah I spotted that & fixedd it this morning.
